### ISSUE TITLE
Large file upload fails after 30 seconds

### ISSUE THREAD

**Issue by hdave** [kubernetes/ingress-gce#102]
I am using GLBC on a Google Cloud cluster - Kubernetes v1.8.  In this instance, the ingress is for the Nexus repository manager and is defined as follows: 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-nexus-https
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
  labels:
    app: ops-nginx
spec:
  tls:
  - hosts:
    - mycorp.com
    secretName: testssl
  backend:
    serviceName: my-nexus
    servicePort: 8081
```

If I then attempt to upload a file to Nexus via curl, it runs for about 30 seconds then fails as follows:

```
curl -i -k -T bigfile https://mycorp.com/repository/testbigfiles/

* GnuTLS recv error (-110): The TLS connection was non-properly terminated.
* Closing connection 0
curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.
```

Logs in Nexus indicate client just dropped:

```
Caused by: org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:791)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:157)
	at org.sonatype.nexus.common.hash.MultiHashingInputStream.read(MultiHashingInputStream.java:66)
	at com.google.common.io.CountingInputStream.read(CountingInputStream.java:63)
	at java.security.DigestInputStream.read(DigestInputStream.java:161)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:106)
	at org.sonatype.nexus.blobstore.file.internal.SimpleFileOperations.create(SimpleFileOperations.java:60)
	at org.sonatype.nexus.blobstore.file.FileBlobStore.lambda$0(FileBlobStore.java:287)
	at org.sonatype.nexus.blobstore.file.FileBlobStore.tryCreate(FileBlobStore.java:350)
```

I did not expect this behavior.  This does not happen if I use the `Type=LoadBalancer` L4 load balancer.  Thinking it might have been the L7's health check, I examined it in the cluster dashboard, but it is reporting healthy.

```
      "ingress.kubernetes.io/backends": "{\"k8s-be-31391--74104f0a9bad5b66\":\"HEALTHY\"}",
```

Any help is appreciated.

**Comment by hdave** [comment]
Turns out, further investigation revealed this is a problem with L7 load balancing in general.  Root cause and workaround is here:  https://stackoverflow.com/questions/40208419/gcp-http-load-balancer-returns-502-error-if-post-data-is-large

**Comment by G-Harmon** [comment]
I'm glad you figured it out!
